enterprisehubs/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from apps.account import views as error

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('apps.bookings.urls')),
    url(r'^backend/', include('apps.members.urls')),
    url(r'^backend/', include('apps.staff.urls')),
    url(r'^backend/', include('apps.billables.urls')),
    url(r'^backend/', include('apps.blog.urls')),
    url(r'^backend/', include('apps.membersite.urls')),
    url(r'^backend/', include('apps.account.urls')),
    url(r'^backend/', include('apps.services.urls')),
    url(r'^backend/', include('apps.facility.urls')),
    url(r'^backend/', include('apps.programs.urls')),
    url(r'^', include('apps.onboarding.urls')),
    url(r'^', include('django.contrib.auth.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler403 = error.error_403
handler404 = error.error_404
handler500 = error.error_500

apps/members/forms.py
from django import forms
from .models import Member, CentralDatabase
from django.contrib.auth.models import User
from .models import MembershipType


class MemberShipRegistrationForm(forms.ModelForm):

    class Meta:
        model = Member
        fields = ['first_name', 'last_name', 'email', 'phone', 'address', 'type', 'username', 'gender',
                  'business_name', 'designation', 'accept_tc', 'valid_id', 'cac']

        widgets = {
            'type': forms.Select(
                attrs={'class': 'form-control js-example-basic-select2', 'placeholder': 'Type'}),
            'gender': forms.Select(
                attrs={'class': 'form-control js-example-basic-select2', 'placeholder': 'Gender'}),
            'first_name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'First Name * ', }),
            'last_name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Last Name *', }),
            'email': forms.EmailInput(
                attrs={'class': 'form-control', 'placeholder': 'Email *'}),
            'phone': forms.NumberInput(
                attrs={'class': 'form-control', 'placeholder': 'Phone *'}),
            'username': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Username *'}),
            'business_name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Company Name *'}),
            'designation': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Designation *'}),
            'address': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Address *'}),

        }

    def clean(self):
        cleaned_data = super(MemberShipRegistrationForm, self).clean()

        username = cleaned_data.get('username')
        email = cleaned_data.get('email')
        type_id = cleaned_data.get('type')

        if User.objects.filter(username=username).exists():
            msg = 'Username is taken'
            self.add_error('username', msg)

        if User.objects.filter(email=email).exists():
            msg = 'A member exist with this email'
            self.add_error('email', msg)

        if cleaned_data.get('accept_tc') is False:
            msg = 'You must accept our T&C to register'
            self.add_error('accept_tc', msg)

        if not cleaned_data.get('cac'):
            try:
                if MembershipType.objects.get(name=type_id).id == 3:
                    msg = 'To register as a black member, CAC document must be uploaded'
                    self.add_error('cac', msg)
            except MembershipType.DoesNotExist:
                pass

        return cleaned_data


class MemberShipUpdateForm(forms.ModelForm):

    class Meta:
        model = Member
        fields = ['date_joined', 'last_pay_date', 'expire_date', 'first_name', 'last_name', 'phone', 'address', 'image', 'cac', 'valid_id']

        widgets = {
            'first_name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'First Name', }),
            'last_name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Last Name', }),
            'phone': forms.NumberInput(
                attrs={'class': 'form-control', 'placeholder': 'Phone'}),
            'address': forms.Textarea(
                attrs={'class': 'form-control', 'placeholder': 'Address'}),
            'date_joined': forms.TextInput(
                attrs={'class': 'form-control'}),
            'last_pay_date': forms.TextInput(
                attrs={'class': 'form-control'}),
            'expire_date': forms.TextInput(
                attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(),
            'cac': forms.ClearableFileInput(),
            'valid_id': forms.ClearableFileInput()
        }


class MemberUpdateSelfForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['phone', 'image']

        widgets = {
            'phone': forms.NumberInput(
                attrs={'class': 'form-control', 'placeholder': 'Phone'}),
            'image': forms.ClearableFileInput()
        }


class ChangePackageType(forms.ModelForm):

    class Meta:
        model = Member
        fields = ('upgrade_type',)

        widgets = {
            'upgrade_type': forms.Select(attrs={'class': 'form-control', 'type': 'select', 'required': 'required'}),
        }


class CreditSelfForm(forms.Form):

    amount = forms.CharField(
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter Amount', 'required': 'required'}))


class ResourceCenterForm(forms.ModelForm):

    class Meta:
        model = CentralDatabase
        exclude = {'owned_by'}
        widgets = {
            'title': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Title', }),
            'docs': forms.ClearableFileInput(
                attrs={'required': 'required'}
            )
        }

templates/backend/wallet/all_credit.html
{% extends 'backend/backend_base.html' %}
{% load static %}
{% load humanize %}

{% block title %}Enterprise Hub - Admin Portal {% endblock title %}
{% block CSS %}
        <!--Data Table-->
        <link href="{% static 'backend/bower_components/datatables/media/css/jquery.dataTables.css' %}" rel="stylesheet">
        <link href="{% static 'backend/bower_components/datatables-tabletools/css/dataTables.tableTools.css' %}" rel="stylesheet">
        <link href="{% static 'backend/bower_components/datatables-colvis/css/dataTables.colVis.css' %}" rel="stylesheet">
        <link href="{% static 'backend/bower_components/datatables-responsive/css/responsive.dataTables.scss' %}" rel="stylesheet">
        <link href="{% static 'backend/bower_components/datatables-scroller/css/scroller.dataTables.scss' %}" rel="stylesheet">

 {% endblock CSS %}

            {% block page_content %}
            <!--main content start-->

            <div id="content" class="ui-content">
                <!--page header start-->
                <div class="page-head-wrap">
                    <h4 class="margin0">
                        Recent Credit
                    </h4>
                    <div class="breadcrumb-right hidden-sm hidden-xs">
                        <ol class="breadcrumb">
                            <li><a href="#">Home</a></li>
{#                            <li><a href="{% url 'new_member' %}">New Member</a></li>#}
{#                            <li class="active">Member List</li>#}
                        </ol>
                    </div>
                </div>
                <!--page header end-->
                <div class="ui-content-body">
                    <div class="ui-container">
                        <div class="row">
                            <div class="col-sm-12">
                                <section class="panel">

                                    <div class="panel-body table-responsive">
                                        <table class="table convert-data-table table-striped">
                                            <thead>
                                                <tr class="text-center">
                                                    <th>
                                                        Transaction ID
                                                    </th>
                                                    <th>
                                                        Customer
                                                    </th>
                                                    <th>
                                                        Amount
                                                    </th>
                                                    <th>
                                                        Date
                                                    </th>
                                                    <th>
                                                        Mode
                                                    </th>
                                                    <th>
                                                        Remark
                                                    </th>
                                                    <th>
                                                        Actions
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            {% for item in object_list %}
                                                <tr>
                                                     <td>
                                                         #{{ item.trans_id }}
                                                    </td>
                                                    <td>
                                                        {% if item.member %}
                                                            <a href="{% url 'member_details' item.member_id %}">{{ item.member.first_name }} {{ item.member.last_name }}</a>
                                                        {% else %}
                                                            GUEST: {{ item.guest_name }}
                                                        {% endif %}
                                                    </td>
                                                    <td>
                                                        ₦{{ item.amount|intcomma }}
                                                    </td>
                                                    <td>
                                                        {{ item.date}}
                                                    </td>
                                                    <td>
                                                    {% if item.is_reversed %}
                                                        <label class="label label-default">Reversed</label>
                                                    {% else %}

                                                        {% if item.payment_mode is 1 %}
                                                            <label class="label label-danger">POS</label>
                                                        {% elif item.payment_mode is 2 %}
                                                            <label class="label label-primary">Transfer</label>
                                                        {% elif item.payment_mode is 3 %}
                                                            <label class="label label-success">Online</label>
                                                        {% endif %}
                                                    {% endif %}
                                                    </td>
                                                    <td>
                                                        {{ item.comment}}
                                                    </td>
                                                    <td>
                                                        {% if item.is_reversed is False %}
                                                        <a href="{% url 'revert_transaction' item.trans_id %}" class="confirm_revert"><button class="btn-xs btn-danger" data-toggle="tooltip" data-placement="top" title="Revert Transaction"><i class="fa fa-arrow-circle-left"></i></button></a>
                                                        {% else %}
                                                            <label class="label label-default"> N/A</label>
                                                        {% endif %}
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </section>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
            <!--main content end-->
            {% endblock page_content %}

{% block Chart_JS %}

{% endblock Chart_JS %}
{% block JS %}
    <!--Data Table-->
        <script src="{% static 'backend/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
{#        <script src="{% static 'bower_components/datatables-tabletools/js/dataTables.tableTools.js' %}"></script>#}
        <script src="{% static 'backend/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
        <script src="{% static 'backend/bower_components/datatables-colvis/js/dataTables.colVis.js' %}"></script>
        <script src="{% static 'backend/bower_components/datatables-responsive/js/dataTables.responsive.js' %}"></script>
        <script src="{% static 'backend/bower_components/datatables-scroller/js/dataTables.scroller.js' %}"></script>

        <!--init data tables-->
        <script src="{% static 'backend/assets/js/init-datatables.js' %}"></script>

{% endblock JS %}

templates/backend/wallet/all_members.html
{% extends 'backend/backend_base.html' %}
{% load static %}

{% block title %}Enterprise Hub - Admin Portal {% endblock title %}
{% block CSS %}
        <!--Data Table-->
        <link href="{% static 'backend/bower_components/datatables/media/css/jquery.dataTables.css' %}" rel="stylesheet">
        <link href="{% static 'backend/bower_components/datatables-tabletools/css/dataTables.tableTools.css' %}" rel="stylesheet">
        <link href="{% static 'backend/bower_components/datatables-colvis/css/dataTables.colVis.css' %}" rel="stylesheet">
        <link href="{% static 'backend/bower_components/datatables-responsive/css/responsive.dataTables.scss' %}" rel="stylesheet">
        <link href="{% static 'backend/bower_components/datatables-scroller/css/scroller.dataTables.scss' %}" rel="stylesheet">

 {% endblock CSS %}

            {% block page_content %}
            <!--main content start-->

            <div id="content" class="ui-content">
                <!--page header start-->
                <div class="page-head-wrap">
                    <h4 class="margin0">
                        All Members
                    </h4>
                    <div class="breadcrumb-right hidden-sm hidden-xs">
                        <ol class="breadcrumb">
                            <li><a href="#">Home</a></li>
                            <li><a href="{% url 'new_member' %}">New Member</a></li>
                            <li class="active">Member List</li>
                        </ol>
                    </div>
                </div>
                <!--page header end-->
                <div class="ui-content-body">
                    <div class="ui-container">
                        <div class="row">
                            <div class="col-sm-12">
                                <section class="panel">

                                    <div class="panel-body table-responsive">
                                        <table class="table convert-data-table table-striped">
                                            <thead>
                                                <tr class="text-center">
                                                    <th>
                                                        Member ID
                                                    </th>
                                                    <th>
                                                        Name
                                                    </th>
                                                    <th>
                                                        Phone
                                                    </th>
                                                    <th>
                                                        Expire_date
                                                    </th>
                                                    <th>
                                                        Status
                                                    </th>
                                                    <th>
                                                        Actions
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            {% for item in member_list %}
                                                <tr>
                                                     <td>
                                                         {{ item.member_id }}
                                                    </td>
                                                    <td>
                                                        {{ item.first_name }} {{ item.last_name }}
                                                    </td>
                                                    <td>
                                                        {{ item.phone}}
                                                    </td>
                                                    <td>
                                                        {{ item.expire_date}}
                                                    </td>
                                                    <td>
                                                        {% if item.is_active == 0 %}
                                                            <label class="label label-danger">not-active</label>
                                                        {% else %}
                                                            <label class="label label-success">active</label>
                                                        {% endif %}
                                                    </td>
                                                    <td>
                                                        <a href="#"><button class="btn-xs btn-primary" data-toggle="tooltip" data-placement="top" title="View Member"><i class="fa fa-eye"></i></button></a>
                                                        <a href="{% url 'update_members' item.member_id %}"><button class="btn-xs btn-default" data-toggle="tooltip" data-placement="top" title="Edit Member Details"><i class="fa fa-edit"></i></button></a>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </section>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
            <!--main content end-->
            {% endblock page_content %}

{% block Chart_JS %}

{% endblock Chart_JS %}
{% block JS %}
    <!--Data Table-->
        <script src="{% static 'backend/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
{#        <script src="{% static 'bower_components/datatables-tabletools/js/dataTables.tableTools.js' %}"></script>#}
        <script src="{% static 'backend/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
        <script src="{% static 'backend/bower_components/datatables-colvis/js/dataTables.colVis.js' %}"></script>
        <script src="{% static 'backend/bower_components/datatables-responsive/js/dataTables.responsive.js' %}"></script>
        <script src="{% static 'backend/bower_components/datatables-scroller/js/dataTables.scroller.js' %}"></script>

        <!--init data tables-->
        <script src="{% static 'backend/assets/js/init-datatables.js' %}"></script>

{% endblock JS %}

templates/backend/wallet/credit_wallet.html
{% extends 'backend/backend_base.html' %}
{% load static %}

{% block title %}LegalStallion - Dashboard {% endblock title %}
{% block CSS %}
    <!-- jQuery Steps Dependencies -->
        <link rel="stylesheet" href="{% static 'backend/bower_components/jquery.steps/demo/css/jquery.steps.css' %}">
        <link rel="stylesheet" href="{% static 'backend/bower_components/select2/dist/css/select2.min.css' %}">
 {% endblock CSS %}

            {% block page_content %}
            <!--main content start-->

            <div id="content" class="ui-content">
                <!--page header start-->
                <div class="page-head-wrap">
                    <h4 class="margin0">
                        Credit Wallet
                    </h4>
                    <div class="breadcrumb-right hidden-sm hidden-xs">
                        <ol class="breadcrumb">
{#                            <li><a href="{% url 'login_dashboard' %}">Home</a></li>#}
{#                            <li><a href="{% url 'client_list' %}">Client List</a></li>#}
{#                            <li class="active">New Client</li>#}
                        </ol>
                    </div>
                </div>
                <!--page header end-->
                <div class="ui-content-body">
                    <div class="ui-container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="panel">
                                    <div class="panel-body">
                                        <form class="form-horizontal " id="commentForm" method="post" action="#" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            {% if form.errors %}
                                                <div class="alert alert-danger alert-dismissible">
                                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                    <span style="margin-left: 10px">{{ form.errors }}</span>
                                                </div>
                                            {% endif %}
                                            {% if user_type is 2 %}
                                            <div class="form-group ">
                                                <label for="select_type" class="control-label col-lg-3">Select Member <span style="color: darkred">*</span></label>
                                                <div class="col-lg-6">
                                                    {{ form.member }}
                                                </div>
                                            </div>
                                            <div class="form-group ">
                                                <label for="select_type" class="control-label col-lg-3">Payment Mode <span style="color: darkred">*</span></label>
                                                <div class="col-lg-6">
                                                    {{ form.payment_mode }}
                                                </div>
                                            </div>

                                            <div class="form-group ">
                                                <label for="select_type" class="control-label col-lg-3">Select Bank <span style="color: darkred">*</span></label>
                                                <div class="col-lg-6">
                                                    <div class="btn-group" data-toggle="buttons">
                                                        {% for bank in bank_account %}
                                                        <label class="btn btn-default">
                                                            <input name="bank" id="bank_acc" type="radio" value="{{ bank.id }}"> {{ bank }}
                                                        </label>
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-group ">
                                                <label for="phone" class="control-label col-lg-3">Amount <span style="color: darkred">*</span></label>
                                                <div class="col-lg-6">
                                                    {{ form.amount }}
                                                </div>
                                            </div>

                                            {% else %}
                                                <div class="form-group ">
                                                    <label for="phone" class="control-label col-lg-3">Amount <span style="color: darkred">*</span></label>
                                                    <div class="col-lg-6">
                                                        <input type="number" name="amount" required placeholder="Enter Amount" class="form-control" id="id_amount" />
                                                    </div>
                                                </div>
                                            {% endif %}

                                            <div class="form-group">
                                                <div class="col-lg-offset-3 col-lg-6">
                                                    <button class="btn btn-primary" type="submit">Submit</button>
                                                </div>
                                            </div>
                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <!--main content end-->
            {% endblock page_content %}

{% block Chart_JS %}

{% endblock Chart_JS %}
{% block JS %}
     <!-- jQuery Steps Dependencies -->
    <script src="{% static 'backend/bower_components/jquery-validation/dist/jquery.validate.min.js' %}"></script>
    <script src="{% static 'backend/bower_components/jquery.steps/build/jquery.steps.min.js' %}"></script>
    <script src="{% static 'backend/assets/js/init-jquery.steps.js' %}"></script>
    <script src="{% static 'backend/assets/js/init-validation.js' %}"></script>
    <script src="{% static 'backend/bower_components/select2/dist/js/select2.min.js' %}"></script>
    <script src="{% static 'backend/assets/js/init-select2.js' %}"></script>

    {% if ref_id %}
        <script src="https://js.paystack.co/v1/inline.js"></script>
        <span onload="payWithPaystack()"></span>
            <script>
              setTimeout(
                  function payWithPaystack(){
                    var handler = PaystackPop.setup({
                      key: 'pk_test_42343126e8e2726e7dd5ea5ee35d889267d62547',
                      email: '{{ member.email }}',
                      amount: {{ amount }}00,
                      ref: '{{ ref_id }}',
                      metadata: {
                         custom_fields: [
                            {
                                display_name: "Mobile Number",
                                variable_name: "mobile_number",
                                value: "+2348012345678"
                            }
                         ]
                      },
                      callback: function(response){
                          {% if ref_id %}
                          window.location = '{% url 'verify_payment' member_id ref_id 'credit_self' %}';
                          {% endif %}

                      },
                      onClose: function(){
                      window.location = '{% url 'credit_self' %}';
                  }
                    });
                    handler.openIframe();
                  },
              0)
            </script>
    {% endif %}
{% endblock JS %}