apps/bookings/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^new_bookings/', views.MemberBookingView.as_view(), name='member_booking'),
    url(r'^all_bookings/', views.AllBookings.as_view(), name='all_bookings'),
    url(r'^edit_bookings/(?P<booking_id>[0-9A-Fa-f-]+)/', views.EditBookings.as_view(), name='edit_bookings'),
    url(r'^secure_booking/(?P<booking_id>[0-9A-Fa-f-]+)/', views.approve_booking, name='secure_booking'),
    url(r'^select_bank/(?P<booking_id>[0-9A-Fa-f-]+)/', views.SelectBank.as_view(), name='select_bank'),
    url(r'^discount_booking/(?P<booking_id>[0-9A-Fa-f-]+)/', views.discount_booking, name='discount_booking'),

    url(r'^delete_booking/(?P<booking_id>[0-9A-Fa-f-]+)/', views.delete_booking, name='delete_booking'),
    url(r'^my_bookings/(?P<member_id>[0-9A-Fa-f-]+)/', views.MyBookings.as_view(), name='my_booking'),
    url(r'^ajax_load_cat/', views.load_ajax_cat, name='ajax_load_cat'),
    url(r'^ajax_load_unit/', views.load_ajax_unit, name='ajax_load_unit'),
    url(r'^load_booked_dates/', views.unit_booked_date, name='unit_booked_date'),
]

enterprisehubs/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from apps.account import views as error

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('apps.bookings.urls')),
    url(r'^backend/', include('apps.members.urls')),
    url(r'^backend/', include('apps.staff.urls')),
    url(r'^backend/', include('apps.billables.urls')),
    url(r'^backend/', include('apps.blog.urls')),
    url(r'^backend/', include('apps.membersite.urls')),
    url(r'^backend/', include('apps.account.urls')),
    url(r'^backend/', include('apps.services.urls')),
    url(r'^backend/', include('apps.facility.urls')),
    url(r'^backend/', include('apps.programs.urls')),
    url(r'^', include('apps.onboarding.urls')),
    url(r'^', include('django.contrib.auth.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler403 = error.error_403
handler404 = error.error_404
handler500 = error.error_500

apps/bookings/models.py
# -*- coding: utf-8 -*-
from django.db import models
from ..facility.models import Facility, Category, Unit
from ..members.models import Member

# Create your models here.


class Bookings(models.Model):

    facility = models.ForeignKey(Facility, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    member = models.ForeignKey(Member, blank=True, null=True, on_delete=models.CASCADE)
    guest_name = models.CharField(max_length=200, blank=True, null=True)
    guest_email = models.EmailField(blank=True, null=True)
    guest_phone = models.CharField(max_length=11, blank=True, null=True)
    date = models.DateField(auto_now_add=True)
    book_from = models.DateField()
    book_to = models.DateField(blank=True, null=True)
    is_secured = models.BooleanField(default=False)
    is_hold = models.BooleanField(default=True)
    is_member = models.BooleanField()
    payable_before_tax = models.DecimalField(decimal_places=2, max_digits=10)
    discount = models.IntegerField(default=0)
    tax = models.DecimalField(decimal_places=2, max_digits=10)
    payable = models.DecimalField(decimal_places=2, max_digits=10)

    class Meta:
        permissions = (
            ('view_all_bookings', 'Can view all bookings'),
            ('approve_bookings', 'Can approve booking'),
        )

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):

        payable = self.amount_payable()
        print(self.discount)
        self.payable_before_tax = payable
        self.tax = payable * 7.5 / 100
        self.payable = (payable + self.tax) - self.discount

        super(Bookings, self).save()

    def amount_payable(self):
        if self.book_to:
            get_days = (self.book_to - self.book_from).days
            payable = self.unit.amount * (get_days + 1)

            return payable
        else:
            payable = self.unit.amount
            return payable


class HeldBookings(models.Model):
    booking = models.ForeignKey(Bookings, on_delete=models.CASCADE)
    date = models.DateField()
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)

apps/bookings/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, TemplateView
from .models import Bookings, HeldBookings
from .forms import MemberBookingForm
from django.contrib import messages
from django.db import transaction
from ..billables.models import WalletBalance, Debit, Income, CashIn, TransactionLog
from ..staff.models import ActivityLog
from ..members.models import Member
from django.shortcuts import redirect
from ..facility.models import Category, Unit
from ..account.models import UserType
from django.shortcuts import render
from datetime import timedelta, datetime
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import permission_required
from ..account.models import BankAcc
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from ..billables.views import post_credit_post_sagamy
from ..staff.models import StaffModel
from ..account.models import HubGL

# Create your views here.


class MemberBookingView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Bookings
    template_name = 'backend/bookings/new_bookings.html'
    form_class = MemberBookingForm
    success_url = reverse_lazy('member_booking')
    raise_exception = True
    permission_required = 'bookings.add_bookings'

    def form_valid(self, form):
        with transaction.atomic():
            book_date = datetime.strptime(str(form.instance.book_from), '%Y-%m-%d')
            form.instance.is_member = True
            try:
                get_member = Member.objects.get(username=self.request.user.username)
                form.instance.member_id = get_member.member_id
            except Member.DoesNotExist:
                pass

            form.save()

            if self.request.POST.get('book_to'):
                end_date = datetime.strptime(str(form.instance.book_to), '%Y-%m-%d')
                delta = end_date - book_date

                for i in range(delta.days + 1):

                    held_book_range = HeldBookings.objects.create(
                        booking_id=form.instance.id,
                        date=book_date + timedelta(i),
                        unit_id=form.instance.unit_id
                    )
                    held_book_range.save()
            else:
                held_book_range = HeldBookings.objects.create(
                    booking_id=form.instance.id,
                    date=book_date,
                    unit_id=form.instance.unit_id
                )
                held_book_range.save()
            messages.success(self.request, 'Your bookings has been created')

        return super(MemberBookingView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(MemberBookingView, self).get_context_data(**kwargs)
        context['held_dates'] = HeldBookings.objects.all()
        return context


def unit_booked_date(request):
    unit_id = request.GET.get('unit')
    booked_date = HeldBookings.objects.filter(unit_id=unit_id)
    return render(request, 'backend/bookings/ajax_load_booked_dates.html', {'booked_dates': booked_date})


def load_ajax_cat(request):
    facility_id = request.GET.get('facility')
    category = Category.objects.filter(facility_id=facility_id)
    return render(request, 'backend/bookings/ajax_load_cate.html', {'category': category})


def load_ajax_unit(request):
    category_id = request.GET.get('category')
    unit = Unit.objects.filter(category_id=category_id)
    return render(request, 'backend/bookings/ajax_load_unit.html', {'unit': unit})


class AllBookings(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Bookings
    template_name = 'backend/bookings/all_bookings.html'
    raise_exception = True
    permission_required = 'bookings.view_all_bookings'

    def get_context_data(self, **kwargs):
        context = super(AllBookings, self).get_context_data(**kwargs)
        context['booking_list'] = Bookings.objects.all().order_by('-id')

        return context


def discount_booking(request, booking_id):
    try:
        amount = int(request.POST['amount'])
        if amount > 0:
            booking = Bookings.objects.get(id=booking_id)
            booking.discount = amount
            booking.save()
            messages.success(request, 'Discount applied to booking')
        else:
            messages.error(request, 'Discount amount cannot be negative or zero')
    except Bookings.DoesNotExist:
        messages.error(request, 'Booking does not exist')

    return redirect('all_bookings')


#  individual booking in member login
class MyBookings(LoginRequiredMixin, ListView):
    model = Bookings
    template_name = 'backend/bookings/all_bookings.html'
    # raise_exception = True

    # def test_func(self):
    #     member = Member.objects.get(username=self.request.user.username).member_id
    #     my_bookings = Bookings.objects.filter(member_id=self.kwargs['member_id'])
    #     for booking in my_bookings:
    #         if booking.member_id == member:
    #             return True
    #         else:
    #             return False

    def get_context_data(self, **kwargs):
        context = super(MyBookings, self).get_context_data(**kwargs)
        context['booking_list'] = Bookings.objects.filter(member_id=self.kwargs['member_id']).order_by('-id')
        return context


class EditBookings(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Bookings
    template_name = 'backend/bookings/new_bookings.html'
    form_class = MemberBookingForm
    pk_url_kwarg = 'booking_id'
    success_url = reverse_lazy('all_bookings')
    raise_exception = True
    permission_required = 'bookings.change_bookings'

    def form_valid(self, form):
        with transaction.atomic():
            unit = self.request.POST.get('unit')
            form.instance.category_id = Unit.objects.get(id=unit).category_id
            form.save()
            messages.success(self.request, 'Your bookings has been edited Successfully')
        return super(EditBookings, self).form_valid(form)


def delete_booking(request, booking_id):
    with transaction.atomic():
        try:
            get_booking = Bookings.objects.get(id=booking_id)

            log = ActivityLog.objects.create(
                log_text='%s deleted a booking of %s with ID #%s' % (request.user.username, get_booking.member,
                                                                     get_booking.id),
                user_id=request.user.id
            )
            log.save()
            user_type = UserType.objects.get(user_id=request.user.id)
            if user_type.account_type == 1:
                get_member = Member.objects.get(username=request.user.username)
                if get_booking.member_id == get_member.member_id:
                    if get_booking.is_secured is False:
                        for item in HeldBookings.objects.filter(booking_id=booking_id):
                            item.delete()
                        get_booking.delete()

                        messages.success(request, 'You have successfully deleted a booking')

                    else:
                        messages.warning(request, 'Error!. This booking cannot be deleted. It is already secured')
                else:
                    messages.error(request, 'Systematic Error. You are trying to delete a booking that isn\'t yours')
            else:
                if get_booking.is_secured is False:
                    for item in HeldBookings.objects.filter(booking_id=booking_id):
                        item.delete()
                    get_booking.delete()

                    messages.success(request, 'You have successfully deleted a booking')

                else:
                    messages.warning(request, 'Error!. This booking cannot be deleted. It is already secured')

        except Bookings.DoesNotExist:
            messages.error(request, 'Systematic Error. No booking exist with that ID')

    return redirect('all_bookings')


class SelectBank(TemplateView):
    template_name = 'backend/bookings/select_bank.html'

    def get_context_data(self, **kwargs):
        context = super(SelectBank, self).get_context_data(**kwargs)
        context['bank_account'] = BankAcc.objects.all()
        return context

    def get_success_url(self):
        return reverse_lazy('secure_booking', self.kwargs['booking_id'])


@permission_required(perm='bookings.approve_bookings', raise_exception=True)
def approve_booking(request, booking_id):
    get_booking = Bookings.objects.get(id=booking_id)
    get_staff = StaffModel.objects.get(user_id=request.user.id)

    with transaction.atomic():
        if get_booking.is_member:
            try:
                wallet_balance = WalletBalance.objects.get(member_id=get_booking.member_id)
                if wallet_balance.amount - get_booking.payable < 0:
                    messages.error(request, 'Error!!! Insufficient Balance')
                else:
                    wallet_balance.amount -= get_booking.payable
                    wallet_balance.save()
                    get_booking.is_secured = True
                    get_booking.save()
                    debit = Debit.objects.create(
                        member_id=get_booking.member_id,
                        amount=get_booking.payable,
                        staff_id=get_staff.id,
                        trans_id=get_booking.id,
                        remarks='Debit transaction for a booking with ID #%s' % get_booking.id

                    )
                    debit.save()

                    log = ActivityLog.objects.create(
                        log_text='%s approve booking of %s with ID of %s' % (request.user.username, get_booking.member,

templates/backend/bookings/ajax_load_booked_dates.html
{% for item in booked_dates %}
    {{ item.date|date:"Y m d" }}
{% endfor %}

templates/backend/bookings/ajax_load_cate.html
<option value="">---------</option>
{% for category in category %}
<option value="{{ category.id }}">{{ category.cat_name }}</option>
{% endfor %}

templates/backend/bookings/ajax_load_unit.html
<option value="">---------</option>
{% for unit in unit %}
<option value="{{ unit.id }}">{{ unit.name }} -- (NGN {{unit.amount}})</option>
{% endfor %}

templates/backend/bookings/new_bookings.html
{% extends 'backend/backend_base.html' %}
{% load static %}

{% block title %}LegalStallion - Dashboard {% endblock title %}
{% block CSS %}
    <!-- jQuery Steps Dependencies -->
        <link rel="stylesheet" href="{% static 'backend/bower_components/jquery.steps/demo/css/jquery.steps.css' %}">
        <link rel="stylesheet" href="{% static 'backend/bower_components/select2/dist/css/select2.min.css' %}">
        <link rel="stylesheet" href="{% static 'backend/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css' %}">
        <style>
        .datepicker table tr td.disabled,
        .datepicker table tr td.disabled:hover {
          background: #d8eefc;
          color: #999999;
          cursor: default;
            }
        </style>
 {% endblock CSS %}

            {% block page_content %}
            <!--main content start-->

            <div id="content" class="ui-content">
                <!--page header start-->
                <div class="page-head-wrap">
                    <h4 class="margin0">
                        Member Booking
                    </h4>
                    <div class="breadcrumb-right hidden-sm hidden-xs">
                        <ol class="breadcrumb">
{#                            <li><a href="{% url 'login_dashboard' %}">Home</a></li>#}
{#                            <li><a href="{% url 'client_list' %}">Client List</a></li>#}
{#                            <li class="active">New Client</li>#}
                        </ol>
                    </div>
                </div>
                <!--page header end-->
                <div class="ui-content-body">
                    <div class="ui-container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="panel">
                                    <div class="panel-body">
                                        <form class="form-horizontal " id="commentForm" method="post"  >
                                            {% csrf_token %}
                                            {% if form.errors %}
                                                <div class="alert alert-danger alert-dismissible">
                                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                    <span style="margin-left: 10px">{{ form.errors }}</span>
                                                </div>
                                            {% endif %}
                                            <div class="form-group ">
                                                <label for="select_type" class="control-label col-lg-3">Facility <span style="color: darkred">*</span></label>
                                                <div class="col-lg-6">
                                                    {{ form.facility }}
                                                </div>
                                            </div>
                                            <div class="form-group ">
                                                <label for="select_type" class="control-label col-lg-3">Category <span style="color: darkred">*</span></label>
                                                <div class="col-lg-6">
                                                    {{ form.category }}
                                                </div>
                                            </div>
                                            <div class="form-group ">
                                                <label for="select_type" class="control-label col-lg-3">Unit <span style="color: darkred">*</span></label>
                                                <div class="col-lg-6">
                                                    {{ form.unit }}
                                                </div>
                                            </div>
                                            {% if user_type is 2 %}
                                            <div class="form-group ">
                                                <label for="email" class="control-label col-lg-3">Member <span style="color: darkred">*</span></label>
                                                <div class="col-lg-6">
                                                    {{ form.member }}
                                                </div>
                                            </div>
                                            {% endif %}
                                              <div class="form-group ">
                                                <label for="email" class="control-label col-lg-3">Book-From<span style="color: darkred">*</span></label>
                                                <div class="col-lg-6">
                                                    <div class="input-group date data-date=" data-date-format="yyyy-mm-dd" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
                                                        <input type="hidden" class="target_datepicker" />
                                                        {{ form.book_from }}
                                                         <span class="input-group-addon"><i class="glyphicon glyphicon-th fa fa-calendar"></i></span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group ">
                                                <label for="email" class="control-label col-lg-3">Book-To </label>
                                                <div class="col-lg-6">
                                                    <div class="input-group date data-date=" data-date-format="yyyy-mm-dd" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
                                                        {{ form.book_to }}
                                                         <span class="input-group-addon"><i class="glyphicon glyphicon-th fa fa-calendar"></i></span>
                                                    </div>
                                                    <small style="color: darkgreen">Select date if booking for a stretch period </small>

                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="col-lg-offset-3 col-lg-6">
                                                    <button class="btn btn-primary" type="submit">Save</button>
                                                </div>
                                            </div>
                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>


            <!--main content end-->
            {% endblock page_content %}

{% block Chart_JS %}

{% endblock Chart_JS %}
{% block JS %}
     <!-- jQuery Steps Dependencies -->
    <script src="{% static 'backend/bower_components/jquery-validation/dist/jquery.validate.min.js' %}"></script>
    <script src="{% static 'backend/assets/js/init-validation.js' %}"></script>
    <script src="{% static 'backend/bower_components/select2/dist/js/select2.min.js' %}"></script>
    <script src="{% static 'backend/assets/js/init-select2.js' %}"></script>
    <script src="{% static 'backend/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
{#    <script src="{% static 'backend/assets/js/init-datepicker.js' %}"></script>#}

    <script>

        $("#id_unit").change(function () {

            let unit_id = $(this).val();

            $.ajax({
                url: {% url 'unit_booked_date' %},
                data: {
                    'unit': unit_id,
                },

                success: function (data) {
                    let ArrVar = data.split("\n");

                    $('.input-group.date').datepicker({
                        autoclose: true,
                        todayHighlight: true,
                        allowClear: true,
                        datesDisabled: ArrVar,
                        daysOfWeekDisabled: [0]

                    });
                }
            })
        });

    </script>

    <script>

    $("#id_facility").change(function () {

      let facility_id = $(this).val();

      $.ajax({

        url: {% url 'ajax_load_cat' %},
        data: {
          'facility': facility_id
        },

        success: function (data) {
          $("#id_category").html(data);
        }
      });
    });

    </script>

    <script>

    $("#id_category").change(function () {
        let category_id = $(this).val();

        $.ajax({

        url: {% url 'ajax_load_unit' %},
        data: {
          'category': category_id
        },

        success: function (data) {

          $("#id_unit").html(data);
        }
      });
    });
    </script>

{% endblock JS %}

templates/backend/bookings/select_bank.html
{% extends 'backend/backend_base.html' %}
{% load static %}

{% block title %}LegalStallion - Dashboard {% endblock title %}
{% block CSS %}

 {% endblock CSS %}

            {% block page_content %}
            <!--main content start-->

            <div id="content" class="ui-content">
                <!--page header start-->
                <div class="page-head-wrap">
                    <h4 class="margin0">
                        Select Bank
                    </h4>
                    <div class="breadcrumb-right hidden-sm hidden-xs">
                        <ol class="breadcrumb">
{#                            <li><a href="{% url 'login_dashboard' %}">Home</a></li>#}
{#                            <li><a href="{% url 'client_list' %}">Client List</a></li>#}
{#                            <li class="active">New Client</li>#}
                        </ol>
                    </div>
                </div>
                <!--page header end-->
                <div class="ui-content-body">
                    <div class="ui-container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="panel">
                                    <div class="panel-body">
                                        <form class="form-horizontal " id="commentForm" method="post" action="{% url 'secure_booking' booking_id %}" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            {% if form.errors %}
                                                <div class="alert alert-danger alert-dismissible">
                                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                    <span style="margin-left: 10px">{{ form.errors }}</span>
                                                </div>
                                            {% endif %}
                                            <div class="form-group ">
                                                <label for="select_type" class="control-label col-lg-3">Select Bank <span style="color: darkred">*</span></label>
                                                <div class="col-lg-6">
                                                    <div class="btn-group" data-toggle="buttons">
                                                        {% for bank in bank_account %}
                                                        <label class="btn btn-default">
                                                            <input required name="bank" id="bank_acc" type="radio" value="{{ bank.id }}"> {{ bank }}
                                                        </label>
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <div class="col-lg-offset-3 col-lg-6">
                                                    <button class="btn btn-primary" type="submit">Submit</button>
                                                </div>
                                            </div>
                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <!--main content end-->
            {% endblock page_content %}

{% block Chart_JS %}

{% endblock Chart_JS %}
{% block JS %}
     <!-- jQuery Steps Dependencies -->
    <script src="{% static 'backend/bower_components/jquery/dist/jquery.min.js"' %}"></script>
    <script src="{% static 'backend/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'backend/bower_components/jquery.nicescroll/dist/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static 'backend/bower_components/autosize/dist/autosize.min.js' %}"></script>

{% endblock JS %}